-- Generated by scripts/generate-schema.js from the application model.
INSERT INTO categories VALUES ('cpu','CPU','CPU');
CREATE TABLE cpu (
  product_id INTEGER PRIMARY KEY REFERENCES products(id),
  manufacturer TEXT,
  family TEXT,
  generation TEXT,
  socket TEXT,
  microarchitecture TEXT,
  core_family TEXT,
  base_clock_ghz REAL,
  boost_clock_ghz REAL,
  tdp_w REAL,
  ppt_w REAL,
  max_memory_gb REAL,
  core_count INTEGER,
  thread_count INTEGER,
  performance_cores INTEGER,
  efficiency_cores INTEGER,
  includes_cooler INTEGER
);
CREATE INDEX cpu_family_cores ON cpu(manufacturer,family,core_count,product_id);
CREATE INDEX cpu_socket ON cpu(socket,product_id);
INSERT INTO categories VALUES ('memory','RAM','MEM');
CREATE TABLE memory (
  product_id INTEGER PRIMARY KEY REFERENCES products(id),
  ram_type TEXT,
  form_factor TEXT,
  ecc TEXT,
  registered TEXT,
  capacity_gb REAL,
  module_capacity_gb REAL,
  speed REAL,
  cas_latency REAL,
  height_mm REAL,
  voltage REAL,
  kit_quantity INTEGER,
  xmp INTEGER,
  expo INTEGER
);
CREATE INDEX memory_type_speed ON memory(ram_type,speed,capacity_gb,product_id);
INSERT INTO categories VALUES ('motherboard','Motherboard','M/B');
CREATE TABLE motherboard (
  product_id INTEGER PRIMARY KEY REFERENCES products(id),
  socket TEXT,
  chipset TEXT,
  form_factor TEXT,
  ram_type TEXT,
  max_memory_gb REAL,
  memory_slots INTEGER,
  m2_slots INTEGER,
  sata_ports INTEGER,
  back_connect INTEGER
);
CREATE INDEX motherboard_socket_memory ON motherboard(socket,ram_type,form_factor,product_id);
INSERT INTO categories VALUES ('gpu','GPU','GPU');
CREATE TABLE gpu (
  product_id INTEGER PRIMARY KEY REFERENCES products(id),
  chip_vendor TEXT,
  chipset TEXT,
  chip_series TEXT,
  memory_type TEXT,
  interface TEXT,
  vram_gb REAL,
  length_mm REAL,
  tdp_w REAL,
  boost_clock_mhz REAL,
  slot_width REAL,
  pcie_generation REAL,
  pcie_lanes INTEGER,
  pcie_6_pin INTEGER,
  pcie_8_pin INTEGER,
  pcie_12vhpwr INTEGER,
  pcie_12v_2x6 INTEGER
);
CREATE INDEX gpu_vendor_vram ON gpu(chip_vendor,vram_gb,length_mm,product_id);
CREATE INDEX gpu_length ON gpu(length_mm,product_id);
CREATE INDEX gpu_series_vram ON gpu(chip_vendor,chip_series,vram_gb,product_id);
INSERT INTO categories VALUES ('storage','Storage','Storage');
CREATE TABLE storage (
  product_id INTEGER PRIMARY KEY REFERENCES products(id),
  storage_type TEXT,
  form_factor TEXT,
  interface TEXT,
  capacity_gb REAL,
  pcie_generation REAL,
  cache_mb REAL,
  pcie_lanes INTEGER,
  nvme INTEGER
);
CREATE INDEX storage_capacity ON storage(capacity_gb,product_id);
CREATE INDEX storage_type_capacity ON storage(storage_type,capacity_gb,product_id);
INSERT INTO categories VALUES ('psu','PSU','PSU');
CREATE TABLE psu (
  product_id INTEGER PRIMARY KEY REFERENCES products(id),
  form_factor TEXT,
  efficiency_rating TEXT,
  modular TEXT,
  wattage REAL,
  length_mm REAL,
  atx_24_pin INTEGER,
  eps_8_pin INTEGER,
  pcie_12vhpwr INTEGER,
  pcie_6_plus_2_pin INTEGER
);
CREATE INDEX psu_form_wattage ON psu(form_factor,wattage,product_id);
CREATE INDEX psu_wattage ON psu(wattage,product_id);
INSERT INTO categories VALUES ('case','PCCase','Case');
CREATE TABLE pc_case (
  product_id INTEGER PRIMARY KEY REFERENCES products(id),
  form_factor TEXT,
  max_gpu_length_mm REAL,
  max_cpu_cooler_height_mm REAL,
  max_psu_length_mm REAL,
  depth_mm REAL,
  width_mm REAL,
  height_mm REAL,
  volume_l REAL,
  expansion_slots INTEGER,
  supports_back_connect INTEGER
);
CREATE INDEX case_gpu_clearance ON pc_case(max_gpu_length_mm,product_id);
INSERT INTO categories VALUES ('case_fan','CaseFan','Case Fan');
CREATE TABLE case_fan (
  product_id INTEGER PRIMARY KEY REFERENCES products(id),
  connector TEXT,
  flow_direction TEXT,
  size_mm REAL,
  airflow_min_cfm REAL,
  airflow_max_cfm REAL,
  noise_min_db REAL,
  noise_max_db REAL,
  static_pressure_mmh2o REAL,
  quantity INTEGER,
  pwm INTEGER
);
CREATE INDEX fan_size_airflow ON case_fan(size_mm,airflow_max_cfm,product_id);
INSERT INTO categories VALUES ('cpu_cooler','CPUCooler','CPU Cooler');
CREATE TABLE cpu_cooler (
  product_id INTEGER PRIMARY KEY REFERENCES products(id),
  height_mm REAL,
  radiator_size_mm REAL,
  noise_min_db REAL,
  noise_max_db REAL,
  fan_size_mm REAL,
  rpm_min REAL,
  rpm_max REAL,
  water_cooled INTEGER,
  fan_quantity INTEGER
);
CREATE INDEX cooler_type_height ON cpu_cooler(water_cooled,height_mm,product_id);
CREATE INDEX cooler_radiator ON cpu_cooler(radiator_size_mm,product_id);
CREATE TRIGGER ingest_product AFTER INSERT ON ingest BEGIN
  INSERT INTO products(source,upstream_id,upstream_key,category,manufacturer,name,series,variant,release_year,manufacturer_url,identity_version,content_hash,source_commit,normalization_version)
  VALUES('buildcores',json_extract(new.payload,'$.product.upstream_id'),json_extract(new.payload,'$.product.upstream_key'),json_extract(new.payload,'$.product.category'),json_extract(new.payload,'$.product.manufacturer'),json_extract(new.payload,'$.product.name'),json_extract(new.payload,'$.product.series'),json_extract(new.payload,'$.product.variant'),json_extract(new.payload,'$.product.release_year'),json_extract(new.payload,'$.product.manufacturer_url'),json_extract(new.payload,'$.product.identity_version'),json_extract(new.payload,'$.product.content_hash'),json_extract(new.payload,'$.product.source_commit'),json_extract(new.payload,'$.product.normalization_version'))
  ON CONFLICT(source,upstream_key) DO UPDATE SET
    upstream_id=excluded.upstream_id,category=excluded.category,manufacturer=excluded.manufacturer,name=excluded.name,series=excluded.series,variant=excluded.variant,release_year=excluded.release_year,manufacturer_url=excluded.manufacturer_url,identity_version=excluded.identity_version,content_hash=excluded.content_hash,source_commit=excluded.source_commit,normalization_version=excluded.normalization_version,
    active=1,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now');
  INSERT INTO upstream_raw VALUES((SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.raw'))
    ON CONFLICT(product_id) DO UPDATE SET raw_json=excluded.raw_json;
  DELETE FROM upstream_identifiers WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key'));
  INSERT INTO upstream_identifiers(product_id,type,value,value_key,region,origin_field)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(value,'$.type'),json_extract(value,'$.value'),json_extract(value,'$.value_key'),json_extract(value,'$.region'),json_extract(value,'$.origin_field')
    FROM json_each(new.payload,'$.identifiers');
  DELETE FROM product_facets WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key'));
  INSERT INTO product_facets(product_id,attribute,value)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(value,'$.attribute'),json_extract(value,'$.value') FROM json_each(new.payload,'$.facets');
  DELETE FROM product_fts WHERE rowid=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key'));
  INSERT INTO product_fts(rowid,text) VALUES((SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.search_text'));
  DELETE FROM cpu WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'cpu';
  INSERT INTO cpu(product_id,manufacturer,family,generation,socket,microarchitecture,core_family,base_clock_ghz,boost_clock_ghz,tdp_w,ppt_w,max_memory_gb,core_count,thread_count,performance_cores,efficiency_cores,includes_cooler)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.manufacturer'),json_extract(new.payload,'$.spec.family'),json_extract(new.payload,'$.spec.generation'),json_extract(new.payload,'$.spec.socket'),json_extract(new.payload,'$.spec.microarchitecture'),json_extract(new.payload,'$.spec.core_family'),json_extract(new.payload,'$.spec.base_clock_ghz'),json_extract(new.payload,'$.spec.boost_clock_ghz'),json_extract(new.payload,'$.spec.tdp_w'),json_extract(new.payload,'$.spec.ppt_w'),json_extract(new.payload,'$.spec.max_memory_gb'),json_extract(new.payload,'$.spec.core_count'),json_extract(new.payload,'$.spec.thread_count'),json_extract(new.payload,'$.spec.performance_cores'),json_extract(new.payload,'$.spec.efficiency_cores'),json_extract(new.payload,'$.spec.includes_cooler') WHERE json_extract(new.payload,'$.product.category')='cpu'
    ON CONFLICT(product_id) DO UPDATE SET manufacturer=excluded.manufacturer,family=excluded.family,generation=excluded.generation,socket=excluded.socket,microarchitecture=excluded.microarchitecture,core_family=excluded.core_family,base_clock_ghz=excluded.base_clock_ghz,boost_clock_ghz=excluded.boost_clock_ghz,tdp_w=excluded.tdp_w,ppt_w=excluded.ppt_w,max_memory_gb=excluded.max_memory_gb,core_count=excluded.core_count,thread_count=excluded.thread_count,performance_cores=excluded.performance_cores,efficiency_cores=excluded.efficiency_cores,includes_cooler=excluded.includes_cooler;
  DELETE FROM memory WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'memory';
  INSERT INTO memory(product_id,ram_type,form_factor,ecc,registered,capacity_gb,module_capacity_gb,speed,cas_latency,height_mm,voltage,kit_quantity,xmp,expo)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.ram_type'),json_extract(new.payload,'$.spec.form_factor'),json_extract(new.payload,'$.spec.ecc'),json_extract(new.payload,'$.spec.registered'),json_extract(new.payload,'$.spec.capacity_gb'),json_extract(new.payload,'$.spec.module_capacity_gb'),json_extract(new.payload,'$.spec.speed'),json_extract(new.payload,'$.spec.cas_latency'),json_extract(new.payload,'$.spec.height_mm'),json_extract(new.payload,'$.spec.voltage'),json_extract(new.payload,'$.spec.kit_quantity'),json_extract(new.payload,'$.spec.xmp'),json_extract(new.payload,'$.spec.expo') WHERE json_extract(new.payload,'$.product.category')='memory'
    ON CONFLICT(product_id) DO UPDATE SET ram_type=excluded.ram_type,form_factor=excluded.form_factor,ecc=excluded.ecc,registered=excluded.registered,capacity_gb=excluded.capacity_gb,module_capacity_gb=excluded.module_capacity_gb,speed=excluded.speed,cas_latency=excluded.cas_latency,height_mm=excluded.height_mm,voltage=excluded.voltage,kit_quantity=excluded.kit_quantity,xmp=excluded.xmp,expo=excluded.expo;
  DELETE FROM motherboard WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'motherboard';
  INSERT INTO motherboard(product_id,socket,chipset,form_factor,ram_type,max_memory_gb,memory_slots,m2_slots,sata_ports,back_connect)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.socket'),json_extract(new.payload,'$.spec.chipset'),json_extract(new.payload,'$.spec.form_factor'),json_extract(new.payload,'$.spec.ram_type'),json_extract(new.payload,'$.spec.max_memory_gb'),json_extract(new.payload,'$.spec.memory_slots'),json_extract(new.payload,'$.spec.m2_slots'),json_extract(new.payload,'$.spec.sata_ports'),json_extract(new.payload,'$.spec.back_connect') WHERE json_extract(new.payload,'$.product.category')='motherboard'
    ON CONFLICT(product_id) DO UPDATE SET socket=excluded.socket,chipset=excluded.chipset,form_factor=excluded.form_factor,ram_type=excluded.ram_type,max_memory_gb=excluded.max_memory_gb,memory_slots=excluded.memory_slots,m2_slots=excluded.m2_slots,sata_ports=excluded.sata_ports,back_connect=excluded.back_connect;
  DELETE FROM gpu WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'gpu';
  INSERT INTO gpu(product_id,chip_vendor,chipset,chip_series,memory_type,interface,vram_gb,length_mm,tdp_w,boost_clock_mhz,slot_width,pcie_generation,pcie_lanes,pcie_6_pin,pcie_8_pin,pcie_12vhpwr,pcie_12v_2x6)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.chip_vendor'),json_extract(new.payload,'$.spec.chipset'),json_extract(new.payload,'$.spec.chip_series'),json_extract(new.payload,'$.spec.memory_type'),json_extract(new.payload,'$.spec.interface'),json_extract(new.payload,'$.spec.vram_gb'),json_extract(new.payload,'$.spec.length_mm'),json_extract(new.payload,'$.spec.tdp_w'),json_extract(new.payload,'$.spec.boost_clock_mhz'),json_extract(new.payload,'$.spec.slot_width'),json_extract(new.payload,'$.spec.pcie_generation'),json_extract(new.payload,'$.spec.pcie_lanes'),json_extract(new.payload,'$.spec.pcie_6_pin'),json_extract(new.payload,'$.spec.pcie_8_pin'),json_extract(new.payload,'$.spec.pcie_12vhpwr'),json_extract(new.payload,'$.spec.pcie_12v_2x6') WHERE json_extract(new.payload,'$.product.category')='gpu'
    ON CONFLICT(product_id) DO UPDATE SET chip_vendor=excluded.chip_vendor,chipset=excluded.chipset,chip_series=excluded.chip_series,memory_type=excluded.memory_type,interface=excluded.interface,vram_gb=excluded.vram_gb,length_mm=excluded.length_mm,tdp_w=excluded.tdp_w,boost_clock_mhz=excluded.boost_clock_mhz,slot_width=excluded.slot_width,pcie_generation=excluded.pcie_generation,pcie_lanes=excluded.pcie_lanes,pcie_6_pin=excluded.pcie_6_pin,pcie_8_pin=excluded.pcie_8_pin,pcie_12vhpwr=excluded.pcie_12vhpwr,pcie_12v_2x6=excluded.pcie_12v_2x6;
  DELETE FROM storage WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'storage';
  INSERT INTO storage(product_id,storage_type,form_factor,interface,capacity_gb,pcie_generation,cache_mb,pcie_lanes,nvme)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.storage_type'),json_extract(new.payload,'$.spec.form_factor'),json_extract(new.payload,'$.spec.interface'),json_extract(new.payload,'$.spec.capacity_gb'),json_extract(new.payload,'$.spec.pcie_generation'),json_extract(new.payload,'$.spec.cache_mb'),json_extract(new.payload,'$.spec.pcie_lanes'),json_extract(new.payload,'$.spec.nvme') WHERE json_extract(new.payload,'$.product.category')='storage'
    ON CONFLICT(product_id) DO UPDATE SET storage_type=excluded.storage_type,form_factor=excluded.form_factor,interface=excluded.interface,capacity_gb=excluded.capacity_gb,pcie_generation=excluded.pcie_generation,cache_mb=excluded.cache_mb,pcie_lanes=excluded.pcie_lanes,nvme=excluded.nvme;
  DELETE FROM psu WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'psu';
  INSERT INTO psu(product_id,form_factor,efficiency_rating,modular,wattage,length_mm,atx_24_pin,eps_8_pin,pcie_12vhpwr,pcie_6_plus_2_pin)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.form_factor'),json_extract(new.payload,'$.spec.efficiency_rating'),json_extract(new.payload,'$.spec.modular'),json_extract(new.payload,'$.spec.wattage'),json_extract(new.payload,'$.spec.length_mm'),json_extract(new.payload,'$.spec.atx_24_pin'),json_extract(new.payload,'$.spec.eps_8_pin'),json_extract(new.payload,'$.spec.pcie_12vhpwr'),json_extract(new.payload,'$.spec.pcie_6_plus_2_pin') WHERE json_extract(new.payload,'$.product.category')='psu'
    ON CONFLICT(product_id) DO UPDATE SET form_factor=excluded.form_factor,efficiency_rating=excluded.efficiency_rating,modular=excluded.modular,wattage=excluded.wattage,length_mm=excluded.length_mm,atx_24_pin=excluded.atx_24_pin,eps_8_pin=excluded.eps_8_pin,pcie_12vhpwr=excluded.pcie_12vhpwr,pcie_6_plus_2_pin=excluded.pcie_6_plus_2_pin;
  DELETE FROM pc_case WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'case';
  INSERT INTO pc_case(product_id,form_factor,max_gpu_length_mm,max_cpu_cooler_height_mm,max_psu_length_mm,depth_mm,width_mm,height_mm,volume_l,expansion_slots,supports_back_connect)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.form_factor'),json_extract(new.payload,'$.spec.max_gpu_length_mm'),json_extract(new.payload,'$.spec.max_cpu_cooler_height_mm'),json_extract(new.payload,'$.spec.max_psu_length_mm'),json_extract(new.payload,'$.spec.depth_mm'),json_extract(new.payload,'$.spec.width_mm'),json_extract(new.payload,'$.spec.height_mm'),json_extract(new.payload,'$.spec.volume_l'),json_extract(new.payload,'$.spec.expansion_slots'),json_extract(new.payload,'$.spec.supports_back_connect') WHERE json_extract(new.payload,'$.product.category')='case'
    ON CONFLICT(product_id) DO UPDATE SET form_factor=excluded.form_factor,max_gpu_length_mm=excluded.max_gpu_length_mm,max_cpu_cooler_height_mm=excluded.max_cpu_cooler_height_mm,max_psu_length_mm=excluded.max_psu_length_mm,depth_mm=excluded.depth_mm,width_mm=excluded.width_mm,height_mm=excluded.height_mm,volume_l=excluded.volume_l,expansion_slots=excluded.expansion_slots,supports_back_connect=excluded.supports_back_connect;
  DELETE FROM case_fan WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'case_fan';
  INSERT INTO case_fan(product_id,connector,flow_direction,size_mm,airflow_min_cfm,airflow_max_cfm,noise_min_db,noise_max_db,static_pressure_mmh2o,quantity,pwm)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.connector'),json_extract(new.payload,'$.spec.flow_direction'),json_extract(new.payload,'$.spec.size_mm'),json_extract(new.payload,'$.spec.airflow_min_cfm'),json_extract(new.payload,'$.spec.airflow_max_cfm'),json_extract(new.payload,'$.spec.noise_min_db'),json_extract(new.payload,'$.spec.noise_max_db'),json_extract(new.payload,'$.spec.static_pressure_mmh2o'),json_extract(new.payload,'$.spec.quantity'),json_extract(new.payload,'$.spec.pwm') WHERE json_extract(new.payload,'$.product.category')='case_fan'
    ON CONFLICT(product_id) DO UPDATE SET connector=excluded.connector,flow_direction=excluded.flow_direction,size_mm=excluded.size_mm,airflow_min_cfm=excluded.airflow_min_cfm,airflow_max_cfm=excluded.airflow_max_cfm,noise_min_db=excluded.noise_min_db,noise_max_db=excluded.noise_max_db,static_pressure_mmh2o=excluded.static_pressure_mmh2o,quantity=excluded.quantity,pwm=excluded.pwm;
  DELETE FROM cpu_cooler WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'cpu_cooler';
  INSERT INTO cpu_cooler(product_id,height_mm,radiator_size_mm,noise_min_db,noise_max_db,fan_size_mm,rpm_min,rpm_max,water_cooled,fan_quantity)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.height_mm'),json_extract(new.payload,'$.spec.radiator_size_mm'),json_extract(new.payload,'$.spec.noise_min_db'),json_extract(new.payload,'$.spec.noise_max_db'),json_extract(new.payload,'$.spec.fan_size_mm'),json_extract(new.payload,'$.spec.rpm_min'),json_extract(new.payload,'$.spec.rpm_max'),json_extract(new.payload,'$.spec.water_cooled'),json_extract(new.payload,'$.spec.fan_quantity') WHERE json_extract(new.payload,'$.product.category')='cpu_cooler'
    ON CONFLICT(product_id) DO UPDATE SET height_mm=excluded.height_mm,radiator_size_mm=excluded.radiator_size_mm,noise_min_db=excluded.noise_min_db,noise_max_db=excluded.noise_max_db,fan_size_mm=excluded.fan_size_mm,rpm_min=excluded.rpm_min,rpm_max=excluded.rpm_max,water_cooled=excluded.water_cooled,fan_quantity=excluded.fan_quantity;
  DELETE FROM ingest WHERE id=new.id;
END;
