-- Generated by scripts/generate-schema.js from the application model.
INSERT INTO categories VALUES ('accessory','Accessory','Accessory');
CREATE TABLE accessory (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('capture_card','CaptureCard','Capture Card');
CREATE TABLE capture_card (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('chair','Chair','Chair');
CREATE TABLE chair (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('desk','Desk','Desk');
CREATE TABLE desk (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('headphones','Headphones','Headphones');
CREATE TABLE headphones (
  product_id INTEGER PRIMARY KEY REFERENCES products(id),
  headphone_type TEXT,
  ear_cup_type TEXT,
  driver_size_mm REAL,
  weight_g REAL,
  battery_life_hours REAL,
  has_microphone INTEGER
);
CREATE INDEX headphones_type_weight ON headphones(headphone_type,weight_g,product_id);
INSERT INTO categories VALUES ('keyboard','Keyboard','Keyboard');
CREATE TABLE keyboard (
  product_id INTEGER PRIMARY KEY REFERENCES products(id),
  switch_model TEXT,
  switch_type TEXT,
  size TEXT,
  layout TEXT,
  hot_swappable INTEGER,
  polling_rate_hz REAL,
  battery_capacity_mah REAL
);
CREATE INDEX keyboard_size_switch ON keyboard(size,switch_type,product_id);
CREATE INDEX keyboard_polling ON keyboard(polling_rate_hz,product_id);
INSERT INTO categories VALUES ('laptop','Laptop','Laptop');
CREATE TABLE laptop (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('lighting','Lighting','Lighting');
CREATE TABLE lighting (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('microphone','Microphone','Microphone');
CREATE TABLE microphone (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('monitor','Monitor','Monitor');
CREATE TABLE monitor (
  product_id INTEGER PRIMARY KEY REFERENCES products(id),
  screen_size_inches REAL,
  resolution_width INTEGER,
  resolution_height INTEGER,
  refresh_rate_hz REAL,
  panel_type TEXT,
  response_time_ms REAL,
  hdr TEXT,
  brightness_nits REAL,
  adaptive_sync TEXT,
  aspect_ratio TEXT
);
CREATE INDEX monitor_resolution_refresh ON monitor(resolution_width,resolution_height,refresh_rate_hz,product_id);
CREATE INDEX monitor_size ON monitor(screen_size_inches,product_id);
INSERT INTO categories VALUES ('mouse','Mouse','Mouse');
CREATE TABLE mouse (
  product_id INTEGER PRIMARY KEY REFERENCES products(id),
  shape TEXT,
  size TEXT,
  sensor TEXT,
  weight_g REAL,
  max_dpi REAL,
  polling_rate_hz REAL,
  buttons INTEGER,
  battery_life_hours REAL,
  length_mm REAL,
  width_mm REAL,
  height_mm REAL
);
CREATE INDEX mouse_shape_weight ON mouse(shape,weight_g,product_id);
CREATE INDEX mouse_polling ON mouse(polling_rate_hz,product_id);
INSERT INTO categories VALUES ('mousepad','Mousepad','Mousepad');
CREATE TABLE mousepad (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('network_card','NetworkCard','Network Card');
CREATE TABLE network_card (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('os','OS','Operating System');
CREATE TABLE os (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('prebuilt_desktop','PrebuiltDesktop','Prebuilt Desktop');
CREATE TABLE prebuilt_desktop (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('sound_card','SoundCard','Sound Card');
CREATE TABLE sound_card (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('speaker','Speaker','Speaker');
CREATE TABLE speaker (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('stand','Stand','Stand');
CREATE TABLE stand (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('thermal_compound','ThermalCompound','Thermal Compound');
CREATE TABLE thermal_compound (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('vr_headset','VRHeadset','VR Headset');
CREATE TABLE vr_headset (
  product_id INTEGER PRIMARY KEY REFERENCES products(id)
);
INSERT INTO categories VALUES ('webcam','Webcam','Webcam');
CREATE TABLE webcam (
  product_id INTEGER PRIMARY KEY REFERENCES products(id),
  resolution TEXT,
  frame_rate_fps INTEGER
);
CREATE INDEX webcam_resolution_fps ON webcam(resolution,frame_rate_fps,product_id);

-- Keep the original BM25 corpus unchanged when unrelated categories are added.
CREATE VIRTUAL TABLE extended_product_fts USING fts5(text,name,manufacturer,series,variant,family,tokenize='unicode61',prefix='2 3 4');
DROP TRIGGER ingest_product;
CREATE TRIGGER ingest_product AFTER INSERT ON ingest BEGIN
  INSERT INTO products(source,upstream_id,upstream_key,category,manufacturer,name,series,variant,release_year,manufacturer_url,identity_version,content_hash,source_commit,normalization_version)
  VALUES('buildcores',json_extract(new.payload,'$.product.upstream_id'),json_extract(new.payload,'$.product.upstream_key'),json_extract(new.payload,'$.product.category'),json_extract(new.payload,'$.product.manufacturer'),json_extract(new.payload,'$.product.name'),json_extract(new.payload,'$.product.series'),json_extract(new.payload,'$.product.variant'),json_extract(new.payload,'$.product.release_year'),json_extract(new.payload,'$.product.manufacturer_url'),json_extract(new.payload,'$.product.identity_version'),json_extract(new.payload,'$.product.content_hash'),json_extract(new.payload,'$.product.source_commit'),json_extract(new.payload,'$.product.normalization_version'))
  ON CONFLICT(source,upstream_key) DO UPDATE SET
    upstream_id=excluded.upstream_id,category=excluded.category,manufacturer=excluded.manufacturer,name=excluded.name,series=excluded.series,variant=excluded.variant,release_year=excluded.release_year,manufacturer_url=excluded.manufacturer_url,identity_version=excluded.identity_version,content_hash=excluded.content_hash,source_commit=excluded.source_commit,normalization_version=excluded.normalization_version,
    active=1,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now');
  INSERT INTO upstream_raw VALUES((SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.raw'))
    ON CONFLICT(product_id) DO UPDATE SET raw_json=excluded.raw_json;
  DELETE FROM upstream_identifiers WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key'));
  INSERT INTO upstream_identifiers(product_id,type,value,value_key,region,origin_field)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(value,'$.type'),json_extract(value,'$.value'),json_extract(value,'$.value_key'),json_extract(value,'$.region'),json_extract(value,'$.origin_field')
    FROM json_each(new.payload,'$.identifiers');
  DELETE FROM product_facets WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key'));
  INSERT INTO product_facets(product_id,attribute,value)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(value,'$.attribute'),json_extract(value,'$.value') FROM json_each(new.payload,'$.facets');
  DELETE FROM product_fts WHERE rowid=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key'));
  INSERT INTO product_fts(rowid,text) SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.search_text') WHERE json_extract(new.payload,'$.product.category') IN ('cpu','memory','motherboard','gpu','storage','psu','case','case_fan','cpu_cooler');
  DELETE FROM extended_product_fts WHERE rowid=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key'));
  INSERT INTO extended_product_fts(rowid,text,name,manufacturer,series,variant,family)
    SELECT p.id,json_extract(new.payload,'$.search_text'),p.name,p.manufacturer,p.series,p.variant,'' FROM products p
    WHERE p.id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND p.category NOT IN ('cpu','memory','motherboard','gpu','storage','psu','case','case_fan','cpu_cooler');
  DELETE FROM cpu WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'cpu';
  INSERT INTO cpu(product_id,manufacturer,family,generation,socket,microarchitecture,core_family,base_clock_ghz,boost_clock_ghz,tdp_w,ppt_w,max_memory_gb,core_count,thread_count,performance_cores,efficiency_cores,includes_cooler)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.manufacturer'),json_extract(new.payload,'$.spec.family'),json_extract(new.payload,'$.spec.generation'),json_extract(new.payload,'$.spec.socket'),json_extract(new.payload,'$.spec.microarchitecture'),json_extract(new.payload,'$.spec.core_family'),json_extract(new.payload,'$.spec.base_clock_ghz'),json_extract(new.payload,'$.spec.boost_clock_ghz'),json_extract(new.payload,'$.spec.tdp_w'),json_extract(new.payload,'$.spec.ppt_w'),json_extract(new.payload,'$.spec.max_memory_gb'),json_extract(new.payload,'$.spec.core_count'),json_extract(new.payload,'$.spec.thread_count'),json_extract(new.payload,'$.spec.performance_cores'),json_extract(new.payload,'$.spec.efficiency_cores'),json_extract(new.payload,'$.spec.includes_cooler') WHERE json_extract(new.payload,'$.product.category')='cpu'
    ON CONFLICT(product_id) DO UPDATE SET manufacturer=excluded.manufacturer,family=excluded.family,generation=excluded.generation,socket=excluded.socket,microarchitecture=excluded.microarchitecture,core_family=excluded.core_family,base_clock_ghz=excluded.base_clock_ghz,boost_clock_ghz=excluded.boost_clock_ghz,tdp_w=excluded.tdp_w,ppt_w=excluded.ppt_w,max_memory_gb=excluded.max_memory_gb,core_count=excluded.core_count,thread_count=excluded.thread_count,performance_cores=excluded.performance_cores,efficiency_cores=excluded.efficiency_cores,includes_cooler=excluded.includes_cooler;
  DELETE FROM memory WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'memory';
  INSERT INTO memory(product_id,ram_type,form_factor,ecc,registered,capacity_gb,module_capacity_gb,speed,cas_latency,height_mm,voltage,kit_quantity,xmp,expo)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.ram_type'),json_extract(new.payload,'$.spec.form_factor'),json_extract(new.payload,'$.spec.ecc'),json_extract(new.payload,'$.spec.registered'),json_extract(new.payload,'$.spec.capacity_gb'),json_extract(new.payload,'$.spec.module_capacity_gb'),json_extract(new.payload,'$.spec.speed'),json_extract(new.payload,'$.spec.cas_latency'),json_extract(new.payload,'$.spec.height_mm'),json_extract(new.payload,'$.spec.voltage'),json_extract(new.payload,'$.spec.kit_quantity'),json_extract(new.payload,'$.spec.xmp'),json_extract(new.payload,'$.spec.expo') WHERE json_extract(new.payload,'$.product.category')='memory'
    ON CONFLICT(product_id) DO UPDATE SET ram_type=excluded.ram_type,form_factor=excluded.form_factor,ecc=excluded.ecc,registered=excluded.registered,capacity_gb=excluded.capacity_gb,module_capacity_gb=excluded.module_capacity_gb,speed=excluded.speed,cas_latency=excluded.cas_latency,height_mm=excluded.height_mm,voltage=excluded.voltage,kit_quantity=excluded.kit_quantity,xmp=excluded.xmp,expo=excluded.expo;
  DELETE FROM motherboard WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'motherboard';
  INSERT INTO motherboard(product_id,socket,chipset,form_factor,ram_type,max_memory_gb,memory_slots,m2_slots,sata_ports,back_connect)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.socket'),json_extract(new.payload,'$.spec.chipset'),json_extract(new.payload,'$.spec.form_factor'),json_extract(new.payload,'$.spec.ram_type'),json_extract(new.payload,'$.spec.max_memory_gb'),json_extract(new.payload,'$.spec.memory_slots'),json_extract(new.payload,'$.spec.m2_slots'),json_extract(new.payload,'$.spec.sata_ports'),json_extract(new.payload,'$.spec.back_connect') WHERE json_extract(new.payload,'$.product.category')='motherboard'
    ON CONFLICT(product_id) DO UPDATE SET socket=excluded.socket,chipset=excluded.chipset,form_factor=excluded.form_factor,ram_type=excluded.ram_type,max_memory_gb=excluded.max_memory_gb,memory_slots=excluded.memory_slots,m2_slots=excluded.m2_slots,sata_ports=excluded.sata_ports,back_connect=excluded.back_connect;
  DELETE FROM gpu WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'gpu';
  INSERT INTO gpu(product_id,chip_vendor,chipset,chip_series,memory_type,interface,vram_gb,length_mm,tdp_w,boost_clock_mhz,slot_width,pcie_generation,pcie_lanes,pcie_6_pin,pcie_8_pin,pcie_12vhpwr,pcie_12v_2x6)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.chip_vendor'),json_extract(new.payload,'$.spec.chipset'),json_extract(new.payload,'$.spec.chip_series'),json_extract(new.payload,'$.spec.memory_type'),json_extract(new.payload,'$.spec.interface'),json_extract(new.payload,'$.spec.vram_gb'),json_extract(new.payload,'$.spec.length_mm'),json_extract(new.payload,'$.spec.tdp_w'),json_extract(new.payload,'$.spec.boost_clock_mhz'),json_extract(new.payload,'$.spec.slot_width'),json_extract(new.payload,'$.spec.pcie_generation'),json_extract(new.payload,'$.spec.pcie_lanes'),json_extract(new.payload,'$.spec.pcie_6_pin'),json_extract(new.payload,'$.spec.pcie_8_pin'),json_extract(new.payload,'$.spec.pcie_12vhpwr'),json_extract(new.payload,'$.spec.pcie_12v_2x6') WHERE json_extract(new.payload,'$.product.category')='gpu'
    ON CONFLICT(product_id) DO UPDATE SET chip_vendor=excluded.chip_vendor,chipset=excluded.chipset,chip_series=excluded.chip_series,memory_type=excluded.memory_type,interface=excluded.interface,vram_gb=excluded.vram_gb,length_mm=excluded.length_mm,tdp_w=excluded.tdp_w,boost_clock_mhz=excluded.boost_clock_mhz,slot_width=excluded.slot_width,pcie_generation=excluded.pcie_generation,pcie_lanes=excluded.pcie_lanes,pcie_6_pin=excluded.pcie_6_pin,pcie_8_pin=excluded.pcie_8_pin,pcie_12vhpwr=excluded.pcie_12vhpwr,pcie_12v_2x6=excluded.pcie_12v_2x6;
  DELETE FROM storage WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'storage';
  INSERT INTO storage(product_id,storage_type,form_factor,interface,capacity_gb,pcie_generation,cache_mb,pcie_lanes,nvme)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.storage_type'),json_extract(new.payload,'$.spec.form_factor'),json_extract(new.payload,'$.spec.interface'),json_extract(new.payload,'$.spec.capacity_gb'),json_extract(new.payload,'$.spec.pcie_generation'),json_extract(new.payload,'$.spec.cache_mb'),json_extract(new.payload,'$.spec.pcie_lanes'),json_extract(new.payload,'$.spec.nvme') WHERE json_extract(new.payload,'$.product.category')='storage'
    ON CONFLICT(product_id) DO UPDATE SET storage_type=excluded.storage_type,form_factor=excluded.form_factor,interface=excluded.interface,capacity_gb=excluded.capacity_gb,pcie_generation=excluded.pcie_generation,cache_mb=excluded.cache_mb,pcie_lanes=excluded.pcie_lanes,nvme=excluded.nvme;
  DELETE FROM psu WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'psu';
  INSERT INTO psu(product_id,form_factor,efficiency_rating,modular,wattage,length_mm,atx_24_pin,eps_8_pin,pcie_12vhpwr,pcie_6_plus_2_pin)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.form_factor'),json_extract(new.payload,'$.spec.efficiency_rating'),json_extract(new.payload,'$.spec.modular'),json_extract(new.payload,'$.spec.wattage'),json_extract(new.payload,'$.spec.length_mm'),json_extract(new.payload,'$.spec.atx_24_pin'),json_extract(new.payload,'$.spec.eps_8_pin'),json_extract(new.payload,'$.spec.pcie_12vhpwr'),json_extract(new.payload,'$.spec.pcie_6_plus_2_pin') WHERE json_extract(new.payload,'$.product.category')='psu'
    ON CONFLICT(product_id) DO UPDATE SET form_factor=excluded.form_factor,efficiency_rating=excluded.efficiency_rating,modular=excluded.modular,wattage=excluded.wattage,length_mm=excluded.length_mm,atx_24_pin=excluded.atx_24_pin,eps_8_pin=excluded.eps_8_pin,pcie_12vhpwr=excluded.pcie_12vhpwr,pcie_6_plus_2_pin=excluded.pcie_6_plus_2_pin;
  DELETE FROM pc_case WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'case';
  INSERT INTO pc_case(product_id,form_factor,max_gpu_length_mm,max_cpu_cooler_height_mm,max_psu_length_mm,depth_mm,width_mm,height_mm,volume_l,expansion_slots,supports_back_connect)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.form_factor'),json_extract(new.payload,'$.spec.max_gpu_length_mm'),json_extract(new.payload,'$.spec.max_cpu_cooler_height_mm'),json_extract(new.payload,'$.spec.max_psu_length_mm'),json_extract(new.payload,'$.spec.depth_mm'),json_extract(new.payload,'$.spec.width_mm'),json_extract(new.payload,'$.spec.height_mm'),json_extract(new.payload,'$.spec.volume_l'),json_extract(new.payload,'$.spec.expansion_slots'),json_extract(new.payload,'$.spec.supports_back_connect') WHERE json_extract(new.payload,'$.product.category')='case'
    ON CONFLICT(product_id) DO UPDATE SET form_factor=excluded.form_factor,max_gpu_length_mm=excluded.max_gpu_length_mm,max_cpu_cooler_height_mm=excluded.max_cpu_cooler_height_mm,max_psu_length_mm=excluded.max_psu_length_mm,depth_mm=excluded.depth_mm,width_mm=excluded.width_mm,height_mm=excluded.height_mm,volume_l=excluded.volume_l,expansion_slots=excluded.expansion_slots,supports_back_connect=excluded.supports_back_connect;
  DELETE FROM case_fan WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'case_fan';
  INSERT INTO case_fan(product_id,connector,flow_direction,size_mm,airflow_min_cfm,airflow_max_cfm,noise_min_db,noise_max_db,static_pressure_mmh2o,quantity,pwm)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.connector'),json_extract(new.payload,'$.spec.flow_direction'),json_extract(new.payload,'$.spec.size_mm'),json_extract(new.payload,'$.spec.airflow_min_cfm'),json_extract(new.payload,'$.spec.airflow_max_cfm'),json_extract(new.payload,'$.spec.noise_min_db'),json_extract(new.payload,'$.spec.noise_max_db'),json_extract(new.payload,'$.spec.static_pressure_mmh2o'),json_extract(new.payload,'$.spec.quantity'),json_extract(new.payload,'$.spec.pwm') WHERE json_extract(new.payload,'$.product.category')='case_fan'
    ON CONFLICT(product_id) DO UPDATE SET connector=excluded.connector,flow_direction=excluded.flow_direction,size_mm=excluded.size_mm,airflow_min_cfm=excluded.airflow_min_cfm,airflow_max_cfm=excluded.airflow_max_cfm,noise_min_db=excluded.noise_min_db,noise_max_db=excluded.noise_max_db,static_pressure_mmh2o=excluded.static_pressure_mmh2o,quantity=excluded.quantity,pwm=excluded.pwm;
  DELETE FROM cpu_cooler WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'cpu_cooler';
  INSERT INTO cpu_cooler(product_id,height_mm,radiator_size_mm,noise_min_db,noise_max_db,fan_size_mm,rpm_min,rpm_max,water_cooled,fan_quantity)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.height_mm'),json_extract(new.payload,'$.spec.radiator_size_mm'),json_extract(new.payload,'$.spec.noise_min_db'),json_extract(new.payload,'$.spec.noise_max_db'),json_extract(new.payload,'$.spec.fan_size_mm'),json_extract(new.payload,'$.spec.rpm_min'),json_extract(new.payload,'$.spec.rpm_max'),json_extract(new.payload,'$.spec.water_cooled'),json_extract(new.payload,'$.spec.fan_quantity') WHERE json_extract(new.payload,'$.product.category')='cpu_cooler'
    ON CONFLICT(product_id) DO UPDATE SET height_mm=excluded.height_mm,radiator_size_mm=excluded.radiator_size_mm,noise_min_db=excluded.noise_min_db,noise_max_db=excluded.noise_max_db,fan_size_mm=excluded.fan_size_mm,rpm_min=excluded.rpm_min,rpm_max=excluded.rpm_max,water_cooled=excluded.water_cooled,fan_quantity=excluded.fan_quantity;
  DELETE FROM accessory WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'accessory';
  INSERT INTO accessory(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='accessory'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM capture_card WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'capture_card';
  INSERT INTO capture_card(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='capture_card'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM chair WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'chair';
  INSERT INTO chair(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='chair'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM desk WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'desk';
  INSERT INTO desk(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='desk'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM headphones WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'headphones';
  INSERT INTO headphones(product_id,headphone_type,ear_cup_type,driver_size_mm,weight_g,battery_life_hours,has_microphone)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.headphone_type'),json_extract(new.payload,'$.spec.ear_cup_type'),json_extract(new.payload,'$.spec.driver_size_mm'),json_extract(new.payload,'$.spec.weight_g'),json_extract(new.payload,'$.spec.battery_life_hours'),json_extract(new.payload,'$.spec.has_microphone') WHERE json_extract(new.payload,'$.product.category')='headphones'
    ON CONFLICT(product_id) DO UPDATE SET headphone_type=excluded.headphone_type,ear_cup_type=excluded.ear_cup_type,driver_size_mm=excluded.driver_size_mm,weight_g=excluded.weight_g,battery_life_hours=excluded.battery_life_hours,has_microphone=excluded.has_microphone;
  DELETE FROM keyboard WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'keyboard';
  INSERT INTO keyboard(product_id,switch_model,switch_type,size,layout,hot_swappable,polling_rate_hz,battery_capacity_mah)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.switch_model'),json_extract(new.payload,'$.spec.switch_type'),json_extract(new.payload,'$.spec.size'),json_extract(new.payload,'$.spec.layout'),json_extract(new.payload,'$.spec.hot_swappable'),json_extract(new.payload,'$.spec.polling_rate_hz'),json_extract(new.payload,'$.spec.battery_capacity_mah') WHERE json_extract(new.payload,'$.product.category')='keyboard'
    ON CONFLICT(product_id) DO UPDATE SET switch_model=excluded.switch_model,switch_type=excluded.switch_type,size=excluded.size,layout=excluded.layout,hot_swappable=excluded.hot_swappable,polling_rate_hz=excluded.polling_rate_hz,battery_capacity_mah=excluded.battery_capacity_mah;
  DELETE FROM laptop WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'laptop';
  INSERT INTO laptop(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='laptop'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM lighting WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'lighting';
  INSERT INTO lighting(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='lighting'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM microphone WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'microphone';
  INSERT INTO microphone(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='microphone'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM monitor WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'monitor';
  INSERT INTO monitor(product_id,screen_size_inches,resolution_width,resolution_height,refresh_rate_hz,panel_type,response_time_ms,hdr,brightness_nits,adaptive_sync,aspect_ratio)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.screen_size_inches'),json_extract(new.payload,'$.spec.resolution_width'),json_extract(new.payload,'$.spec.resolution_height'),json_extract(new.payload,'$.spec.refresh_rate_hz'),json_extract(new.payload,'$.spec.panel_type'),json_extract(new.payload,'$.spec.response_time_ms'),json_extract(new.payload,'$.spec.hdr'),json_extract(new.payload,'$.spec.brightness_nits'),json_extract(new.payload,'$.spec.adaptive_sync'),json_extract(new.payload,'$.spec.aspect_ratio') WHERE json_extract(new.payload,'$.product.category')='monitor'
    ON CONFLICT(product_id) DO UPDATE SET screen_size_inches=excluded.screen_size_inches,resolution_width=excluded.resolution_width,resolution_height=excluded.resolution_height,refresh_rate_hz=excluded.refresh_rate_hz,panel_type=excluded.panel_type,response_time_ms=excluded.response_time_ms,hdr=excluded.hdr,brightness_nits=excluded.brightness_nits,adaptive_sync=excluded.adaptive_sync,aspect_ratio=excluded.aspect_ratio;
  DELETE FROM mouse WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'mouse';
  INSERT INTO mouse(product_id,shape,size,sensor,weight_g,max_dpi,polling_rate_hz,buttons,battery_life_hours,length_mm,width_mm,height_mm)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.shape'),json_extract(new.payload,'$.spec.size'),json_extract(new.payload,'$.spec.sensor'),json_extract(new.payload,'$.spec.weight_g'),json_extract(new.payload,'$.spec.max_dpi'),json_extract(new.payload,'$.spec.polling_rate_hz'),json_extract(new.payload,'$.spec.buttons'),json_extract(new.payload,'$.spec.battery_life_hours'),json_extract(new.payload,'$.spec.length_mm'),json_extract(new.payload,'$.spec.width_mm'),json_extract(new.payload,'$.spec.height_mm') WHERE json_extract(new.payload,'$.product.category')='mouse'
    ON CONFLICT(product_id) DO UPDATE SET shape=excluded.shape,size=excluded.size,sensor=excluded.sensor,weight_g=excluded.weight_g,max_dpi=excluded.max_dpi,polling_rate_hz=excluded.polling_rate_hz,buttons=excluded.buttons,battery_life_hours=excluded.battery_life_hours,length_mm=excluded.length_mm,width_mm=excluded.width_mm,height_mm=excluded.height_mm;
  DELETE FROM mousepad WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'mousepad';
  INSERT INTO mousepad(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='mousepad'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM network_card WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'network_card';
  INSERT INTO network_card(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='network_card'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM os WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'os';
  INSERT INTO os(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='os'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM prebuilt_desktop WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'prebuilt_desktop';
  INSERT INTO prebuilt_desktop(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='prebuilt_desktop'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM sound_card WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'sound_card';
  INSERT INTO sound_card(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='sound_card'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM speaker WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'speaker';
  INSERT INTO speaker(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='speaker'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM stand WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'stand';
  INSERT INTO stand(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='stand'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM thermal_compound WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'thermal_compound';
  INSERT INTO thermal_compound(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='thermal_compound'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM vr_headset WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'vr_headset';
  INSERT INTO vr_headset(product_id)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) WHERE json_extract(new.payload,'$.product.category')='vr_headset'
    ON CONFLICT(product_id) DO NOTHING;
  DELETE FROM webcam WHERE product_id=(SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')) AND json_extract(new.payload,'$.product.category')<>'webcam';
  INSERT INTO webcam(product_id,resolution,frame_rate_fps)
    SELECT (SELECT id FROM products WHERE source='buildcores' AND upstream_key=json_extract(new.payload,'$.product.upstream_key')),json_extract(new.payload,'$.spec.resolution'),json_extract(new.payload,'$.spec.frame_rate_fps') WHERE json_extract(new.payload,'$.product.category')='webcam'
    ON CONFLICT(product_id) DO UPDATE SET resolution=excluded.resolution,frame_rate_fps=excluded.frame_rate_fps;
  DELETE FROM ingest WHERE id=new.id;
END;
