import { readFile, writeFile } from 'node:fs/promises';
import { models } from '../src/model.js';

// Frozen initial migration. For future schema changes add a NEW migration.
// Run --check in CI to catch accidental edits to either representation.
const literal = s => `'${s.replaceAll("'", "''")}'`;
const extract = path => `json_extract(new.payload,'$.${path}')`;
const pid = `(SELECT id FROM products WHERE source='buildcores' AND upstream_key=${extract('product.upstream_key')})`;
const productColumns = ['upstream_id','upstream_key','category','manufacturer','name','series','variant','release_year','manufacturer_url','identity_version','content_hash','source_commit','normalization_version'];
let sql = '-- Generated by scripts/generate-schema.js from the application model.\n';
for (const [category, model] of Object.entries(models)) {
  sql += `INSERT INTO categories VALUES (${literal(category)},${literal(model.upstream)},${literal(model.label)});\n`;
  sql += `CREATE TABLE ${model.table} (\n  product_id INTEGER PRIMARY KEY REFERENCES products(id),\n`;
  sql += Object.entries(model.fields).map(([name, type]) => `  ${name} ${type}`).join(',\n') + '\n);\n';
  for (const [name, columns] of Object.entries(model.indexes)) {
    sql += `CREATE INDEX ${name} ON ${model.table}(${columns.join(',')});\n`;
  }
}
sql += `CREATE TRIGGER ingest_product AFTER INSERT ON ingest BEGIN
  INSERT INTO products(source,${productColumns.join(',')})
  VALUES('buildcores',${productColumns.map(c => extract(`product.${c}`)).join(',')})
  ON CONFLICT(source,upstream_key) DO UPDATE SET
    ${productColumns.filter(c => c !== 'upstream_key').map(c => `${c}=excluded.${c}`).join(',')},
    active=1,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now');
  INSERT INTO upstream_raw VALUES(${pid},${extract('raw')})
    ON CONFLICT(product_id) DO UPDATE SET raw_json=excluded.raw_json;
  DELETE FROM upstream_identifiers WHERE product_id=${pid};
  INSERT INTO upstream_identifiers(product_id,type,value,value_key,region,origin_field)
    SELECT ${pid},json_extract(value,'$.type'),json_extract(value,'$.value'),json_extract(value,'$.value_key'),json_extract(value,'$.region'),json_extract(value,'$.origin_field')
    FROM json_each(new.payload,'$.identifiers');
  DELETE FROM product_facets WHERE product_id=${pid};
  INSERT INTO product_facets(product_id,attribute,value)
    SELECT ${pid},json_extract(value,'$.attribute'),json_extract(value,'$.value') FROM json_each(new.payload,'$.facets');
  DELETE FROM product_fts WHERE rowid=${pid};
  INSERT INTO product_fts(rowid,text) VALUES(${pid},${extract('search_text')});
`;
for (const [category, model] of Object.entries(models)) {
  const columns = Object.keys(model.fields);
  // Delete a stale category row only on a category move, not every ordinary update.
  sql += `  DELETE FROM ${model.table} WHERE product_id=${pid} AND ${extract('product.category')}<>${literal(category)};\n`;
  sql += `  INSERT INTO ${model.table}(product_id,${columns.join(',')})\n`;
  sql += `    SELECT ${pid},${columns.map(c => extract(`spec.${c}`)).join(',')} WHERE ${extract('product.category')}=${literal(category)}\n`;
  sql += `    ON CONFLICT(product_id) DO UPDATE SET ${columns.map(c => `${c}=excluded.${c}`).join(',')};\n`;
}
sql += '  DELETE FROM ingest WHERE id=new.id;\nEND;\n';
const target = new URL('../migrations/0002_specs_ingest.sql', import.meta.url);
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== sql) throw new Error('Generated migration differs; run npm run schema:generate');
  console.log('Schema generator matches migration.');
} else {
  await writeFile(target, sql);
  console.log('Generated migrations/0002_specs_ingest.sql');
}
