import { readFile, writeFile } from 'node:fs/promises';
import { models as registry, initialCategories } from '../src/model.js';
const models = Object.fromEntries(initialCategories.map(category => [category, registry[category]]));

// Frozen initial migration. For future schema changes add a NEW migration.
// Run --check in CI to catch accidental edits to either representation.
const literal = s => `'${s.replaceAll("'", "''")}'`;
const extract = path => `json_extract(new.payload,'$.${path}')`;
const pid = `(SELECT id FROM products WHERE source='buildcores' AND upstream_key=${extract('product.upstream_key')})`;
const productColumns = ['upstream_id','upstream_key','category','manufacturer','name','series','variant','release_year','manufacturer_url','identity_version','content_hash','source_commit','normalization_version'];
function generate(models, { forward = false } = {}) {
let sql = '-- Generated by scripts/generate-schema.js from the application model.\n';
for (const [category, model] of Object.entries(models)) {
  if (forward && initialCategories.includes(category)) continue;
  sql += `INSERT INTO categories VALUES (${literal(category)},${literal(model.upstream)},${literal(model.label)});\n`;
  sql += `CREATE TABLE ${model.table} (\n  product_id INTEGER PRIMARY KEY REFERENCES products(id)`;
  sql += Object.keys(model.fields).length ? ',\n' + Object.entries(model.fields).map(([name, type]) => `  ${name} ${type}`).join(',\n') : '';
  sql += '\n);\n';
  for (const [name, columns] of Object.entries(model.indexes)) {
    sql += `CREATE INDEX ${name} ON ${model.table}(${columns.join(',')});\n`;
  }
}
if (forward) sql += `
-- Keep the original BM25 corpus unchanged when unrelated categories are added.
CREATE VIRTUAL TABLE extended_product_fts USING fts5(text,name,manufacturer,series,variant,family,tokenize='unicode61',prefix='2 3 4');
DROP TRIGGER ingest_product;
`;
sql += `CREATE TRIGGER ingest_product AFTER INSERT ON ingest BEGIN
  INSERT INTO products(source,${productColumns.join(',')})
  VALUES('buildcores',${productColumns.map(c => extract(`product.${c}`)).join(',')})
  ON CONFLICT(source,upstream_key) DO UPDATE SET
    ${productColumns.filter(c => c !== 'upstream_key').map(c => `${c}=excluded.${c}`).join(',')},
    active=1,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now');
  INSERT INTO upstream_raw VALUES(${pid},${extract('raw')})
    ON CONFLICT(product_id) DO UPDATE SET raw_json=excluded.raw_json;
  DELETE FROM upstream_identifiers WHERE product_id=${pid};
  INSERT INTO upstream_identifiers(product_id,type,value,value_key,region,origin_field)
    SELECT ${pid},json_extract(value,'$.type'),json_extract(value,'$.value'),json_extract(value,'$.value_key'),json_extract(value,'$.region'),json_extract(value,'$.origin_field')
    FROM json_each(new.payload,'$.identifiers');
  DELETE FROM product_facets WHERE product_id=${pid};
  INSERT INTO product_facets(product_id,attribute,value)
    SELECT ${pid},json_extract(value,'$.attribute'),json_extract(value,'$.value') FROM json_each(new.payload,'$.facets');
  DELETE FROM product_fts WHERE rowid=${pid};
  ${forward ? `INSERT INTO product_fts(rowid,text) SELECT ${pid},${extract('search_text')} WHERE ${extract('product.category')} IN (${initialCategories.map(literal).join(',')});
  DELETE FROM extended_product_fts WHERE rowid=${pid};
  INSERT INTO extended_product_fts(rowid,text,name,manufacturer,series,variant,family)
    SELECT p.id,${extract('search_text')},p.name,p.manufacturer,p.series,p.variant,'' FROM products p
    WHERE p.id=${pid} AND p.category NOT IN (${initialCategories.map(literal).join(',')});` : `INSERT INTO product_fts(rowid,text) VALUES(${pid},${extract('search_text')});`}
`;
for (const [category, model] of Object.entries(models)) {
  const columns = Object.keys(model.fields);
  // Delete a stale category row only on a category move, not every ordinary update.
  sql += `  DELETE FROM ${model.table} WHERE product_id=${pid} AND ${extract('product.category')}<>${literal(category)};\n`;
  sql += `  INSERT INTO ${model.table}(${['product_id', ...columns].join(',')})\n`;
  sql += `    SELECT ${[pid, ...columns.map(c => extract(`spec.${c}`))].join(',')} WHERE ${extract('product.category')}=${literal(category)}\n`;
  sql += columns.length ? `    ON CONFLICT(product_id) DO UPDATE SET ${columns.map(c => `${c}=excluded.${c}`).join(',')};\n` : '    ON CONFLICT(product_id) DO NOTHING;\n';
}
sql += '  DELETE FROM ingest WHERE id=new.id;\nEND;\n';
return sql;
}
for (const [file, sql] of [
  ['0002_specs_ingest.sql', generate(models)],
  ['0007_all_categories.sql', generate(registry, { forward: true })],
]) {
const target = new URL(`../migrations/${file}`, import.meta.url);
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== sql) throw new Error(`Generated ${file} differs; run npm run schema:generate`);
  console.log(`Schema generator matches ${file}.`);
} else {
  await writeFile(target, sql);
  console.log(`Generated migrations/${file}`);
}
}
